name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest

    

    steps:
    - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Access Secret
      env: TOGGL_API_KEY: ${{secrets.TOGGL_API_KEY}}
      run: echo "The secret is $TOGGL_API_KEY"
