name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          echo "::set-env name=TOGGL_API_KEY::${{ secrets.TOGGL_API_KEY }}"
          npm run deploy
        env:
          SECRET_KEY: ${{ secrets.TOGGL_API_KEY }}
# name: Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: macos-latest

#     steps:
#     - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Access Secret
#       env: TOGGL_API_KEY: ${{secrets.TOGGL_API_KEY}}
#       run: echo "The secret is $TOGGL_API_KEY"
